### ISSUE TITLE
(apache-httpd) IPV6 listen value is missing in httpd.conf

### ISSUE THREAD

**Issue by photodude** [rgra/choco-packages#11]
I recently installed Apache via chocolatey on Windows 7 SP1 and found the IPV6 listen value is missing from the httpd.conf file.

### Expected
an IPV6 listen value such as
`Listen [::0]:80`

### Actual
No IPV6 listen value in the httpd.conf file

/cc @rgra @AdmiringWorm @ferventcoder

**Comment by diovoemor** [comment]
Listen 80
This one directive will listen on all IPv4 & IPv6 IPs that are available on the computer. That's all that is needed unless you want to target a specific IP to listen to (which you're not with [::0]).

**Comment by photodude** [comment]
Thanks @diovoemor I was unaware that `Listen 80` covered both IPv4 and IPv6.

Closing as expected behavior.
