### ISSUE TITLE
Would it be possible to default the server-jre8 to Machine with User as an option

### ISSUE THREAD

**Issue by dragon788** [rgra/choco-packages#2]
Since a lot of the packages that depend on the server-jre pull it without adding any parameters and many of them need to run as a service, with the way that it currently only installs JAVA_HOME to the User's Environment and adds %JAVA_HOME%/bin to the User's PATH, this doesn't end up actually working for most of those server packages because if they run as a service via the SYSTEM account, they can't find Java.exe in the PATH or see JAVA_HOME.

I'll see about making a pull request from my fork with this change, but I wanted to document some of the reasoning behind the change and I'll have to explore how to detect/clean up the User variables so that it doesn't break existing installs that were intentionally NOT system wide.

**Comment by espoelstra** [comment]
@rgra I also noticed that when passing -params to the 'server-jre' package they don't pass through to the server-jre8 unless I also pass --paramsglobal (in any of it's 10 or so aliases). This further makes me think machine-wide should be the default, as requiring a user only install for the 'server' version is a lot less likely than if you were installing the browser plugin and only wanted certain users to have it.

I'll see about creating a pull request soon as this would make it much easier to chain install TeamCity or it's Agent or any other Java requiring software like Tomcat that doesn't include it's own JRE.

**Comment by espoelstra** [comment]
This would be fixed by #3 .

**Comment by espoelstra** [comment]
I've merged #3 so in the future the package will default to system wide installation instead of only setting the JAVA_HOME and updating the PATH for a single user. Version 1.8.0.111 will be the last using USER by default, the .DATE version and higher releases will default to MACHINE.
