### ISSUE TITLE
Getting 404 from Oracle server

### ISSUE THREAD

**Issue by devbeard** [rgra/choco-packages#27]
Getting the following error message when trying to install `server-jre8`:

```Chocolatey v0.10.8
Installing the following packages:
server-jre8
By installing you accept licenses for the packages.
Progress: Downloading server-jre8 8.0.152... 100%

server-jre8 v8.0.152 [Approved]
server-jre8 package files install completed. Performing other installation steps.
ERROR: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."```

**Comment by littlefyr** [comment]
Pull Request #26 should have the fix for this.

**Comment by JorritSalverda** [comment]
In the meantime I'm 'installing' it with the following powershell:

```
$webclient = New-Object System.Net.WebClient
$webclient.Headers.Add([System.Net.HttpRequestHeader]::Cookie, "oraclelicense=a");
$webclient.DownloadFile("http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/server-jre-8u162-windows-x64.tar.gz", "c:\windows\temp\server-jre-windows-x64.tar.gz")
$webclient.Dispose()
Invoke-Expression "cmd /c C:\ProgramData\chocolatey\bin\7za.exe x -oc:\windows\temp c:\windows\temp\server-jre-windows-x64.tar.gz -r"
Invoke-Expression "cmd /c C:\ProgramData\chocolatey\bin\7za.exe x -oc:\ c:\windows\temp\server-jre-windows-x64.tar -r"
[Environment]::SetEnvironmentVariable( "JAVA_HOME", "c:\jdk1.8.0_162\jre\bin", [System.EnvironmentVariableTarget]::Machine )
```

**Comment by jchannon** [comment]
Any movement on this @rgra ?

**Comment by jchannon** [comment]
Is the issue Oracle simply deletes older versions?

**Comment by jchannon** [comment]
@JorritSalverda does `7za.exe` come with chocolately because i ran your script and i got `'C:\ProgramData\chocolatey\bin\7za.exe' is not recognized as an internal or external command,`

**Comment by dragon788** [comment]
Oracle doesn't actually delete the older versions they simply move them behind a login to where they are only accessible via the Oracle Developer pages to download due to the security issues. There is a script called jdk wrapper written in Bash that can use that login information to download older versions, but this package doesn't take advantage of that.

@jchannon 7za comes with chocolatey and is probably only accessible within the Chocolatey PATH eg `C:\ProgramData\chocolatey\bin\` or wherever it is.

**Comment by jchannon** [comment]
That path doesnt work so I've managed to find it in `C:\ProgramData\chocolatey\tools\7z.exe` but now getting an error:

```
Command Line Error:
    Finished
    Too short switch:
    -o
```

**Comment by JorritSalverda** [comment]
Oh yes, I missed this line at the start:

```
cinst 7zip.portable --yes --accept-license --version=16.04
```
