### ISSUE TITLE
(apache-httpd) Error on service start during installation

### ISSUE THREAD

**Issue by uiii** [rgra/choco-packages#7]
There is a problem when the service is started during installation because the `ServerRoot` is set to `/Apache24` so it doesn't match the actual install path. This will throw a not fatal error during installation, however the installation finishes successfully. I'm not sure if this is easily fixable.

**Comment by photodude** [comment]
I'm also seeing this issue. For some reason, the relative paths are not working and have to be set to the explicit path.

I recently wrote a blog post that detailed the issues I had post install to get up and running.
https://brian.teeman.net/joomla/885-install-amp-on-windows-with-chocolatey

/cc @rgra @AdmiringWorm @ferventcoder

**Comment by photodude** [comment]
Looking at the shell output after install I see the following
```ps
Syntax error on line 39 of C:/tools/Apache/httpd-2.4.20/Apache24/conf/httpd.conf: ServerRoot must be a valid directory
```
this is also recorded in the chocolatey.log log file. Something is likely not configured correctly in the default install.

**Comment by photodude** [comment]
apache-httpd has been migrated to core team repo. You should check the current package and if necessary repost in the core team issues. https://github.com/chocolatey/chocolatey-coreteampackages/issues

I believe this specific error may have been addressed
