### ISSUE TITLE
(apache-httpd) Uninstallation deletes whole unzipLocation - possibly dangerous

### ISSUE THREAD

**Issue by uiii** [rgra/choco-packages#8]
Because of the `Apache24` subdirectory created in the `unzipLocation` path, it may tempt to change the path to more general like `C:\tools` so Apache will be placed directly among other programs. But this is quite dangerous, because the uninstallation will remove the `unzipLocation` path completely event with all other apps in it.

**Comment by photodude** [comment]
apache-httpd has been migrated to core team repo. You should check the current package and if necessary repost in the core team issues. https://github.com/chocolatey/chocolatey-coreteampackages/issues

note the install location has changed in the current version via the coreteam, I'm not sure if this is still an issue.
